#! /usr/bin/bash
# usage :
# run on SBC
# > operator
# enter target hostname (default own SBC)

if [ ${HOSTNAME:0:1} == "D" ]; then
  cd /root/ros2_ws/
  source /opt/ros/${ROS_DISTRO}/setup.bash
  source install/setup.bash
  ros2 run teleop_twist_keyboard teleop_twist_keyboard
else
  dup teleop
  COMPOSE_PROJECT_NAME=teleop_${PROJECT} docker compose exec common /common/ros_launcher/operator
fi
